"""
Server-issued, signed conversation identifiers.

Conversation ids used to be generated by the browser (`crypto.randomUUID()`)
and trusted verbatim. That let any client post any id to /chat/* and read
or append to somebody else's conversation -- a plain insecure direct
object reference, with the whole history behind it.

Ids are now minted server-side and returned with an HMAC signature. The
signature can't be produced without the server secret, so a client can
only use ids this server actually issued. Tokens are bearer credentials:
they identify a conversation, not a person, which is the right scope for
an anonymous support widget with no user accounts.
"""

import base64
import hashlib
import hmac
import logging
import os
import secrets

logger = logging.getLogger(__name__)

SESSION_SECRET_ENV = "SESSION_SECRET"

# 16 bytes of urlsafe randomness -- not guessable, and short enough to
# stay readable in logs.
_ID_BYTES = 16


def _load_secret() -> bytes:
    configured = os.environ.get(SESSION_SECRET_ENV, "").strip()
    if configured:
        return configured.encode("utf-8")

    # A generated secret keeps local development working with no setup,
    # but it changes on every restart, which silently invalidates every
    # conversation in flight. That's fine for a dev machine and wrong for
    # a deployment, hence the warning rather than a silent default.
    logger.warning(
        "%s is not set -- generating a temporary one. Conversations will "
        "not survive a restart, and multiple server processes will reject "
        "each other's tokens. Set %s in production.",
        SESSION_SECRET_ENV,
        SESSION_SECRET_ENV,
    )
    return secrets.token_bytes(32)


_SECRET = _load_secret()


def _sign(conversation_id: str) -> str:
    digest = hmac.new(_SECRET, conversation_id.encode("utf-8"), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


def issue_conversation_token() -> str:
    """Mints a fresh conversation id and returns it as `<id>.<signature>`."""
    conversation_id = secrets.token_urlsafe(_ID_BYTES)
    return f"{conversation_id}.{_sign(conversation_id)}"


def verify_conversation_token(token: str) -> str | None:
    """
    Returns the conversation id if `token` carries a valid signature,
    otherwise None. Never raises -- malformed input from the network is
    an expected case, not an error.
    """
    if not token or not isinstance(token, str):
        return None

    conversation_id, separator, signature = token.partition(".")
    if not separator or not conversation_id or not signature:
        return None

    # compare_digest rather than == so a wrong signature can't be
    # narrowed down by timing how long the comparison took.
    if not hmac.compare_digest(signature, _sign(conversation_id)):
        return None

    return conversation_id
